apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: doggo-blackbox-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: blackbox
      rules:
        - alert: ServiceDown
          expr: probe_success == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Сервис недоступен"
            description: "Health-check не отвечает более 1 минуты. Endpoint: {{ $labels.instance }}"
