apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: doggo-health
  namespace: monitoring
  labels:
    release: monitoring
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
  targets:
    staticConfig:
      static:
        - http://doggo.default:4000/actuator/health
        - http://doggo-rating.default:8000/health
